02-Git/README.md

Task is described in the README.md file.
Signed-off-by: Andriy Khulap <andriy.khulap@globallogic.com>

02-Git: Add homework

---

homework/lesson02/main.cpp
homework/lesson02/makefile

Add homework after lesson #2 
Signed-off-by: serega911 <pasechnuy.sergey@gmail.com>

Homework02

---

02-Git/test.txt

This is a test for the PR process.

02 git solution

---

02-Git/main.c

Signed-off-by: Andriy Khulap <andriy.khulap@globallogic.com>

02-Git: Task solution

---

99-test/main.c

Signed-off-by: Andriy Khulap <andriy.khulap@globallogic.com>

99-task: Add simple program

---

02-Git/Makefile
02-Git/homework.c

Create a rock-paper-scissors console game

02-Git homework 

---

02-Git/Makefile
02-Git/src/Makefile
02-Git/src/main.c

Hometask #2
A rock-paper-scissors console game

xvikili_lesson02

---

02-Git/Makefile
02-Git/README.md
02-Git/main.c

This commit contains finished task's source code, build Makefile
and modify Readme.md to provide instructions for build and
execution
Signed-off-by: Serhii Perederii <serhii.perederii@globallogic.com>

02-Git: Add finished task

---

02-Git/main.c
02-Git/makefile

02 git task

---

02-Git/Makefile
02-Git/game.c

Homework has been revised after following comments at review:
"commits with task should not be in this PR (needs to be pushed to your branch before).
makefile commit without code is not buildable
commit with renaming should be removed, and original commit needs to be modified. No patches to patches in unmerged code.
Also no topics and signature."
Change branch to main/Eugene.Ovdiyuk
Made push force to delete all my commits and made 2 commits as I initially wanted, but made mistake.
Not sure about "no topics and signature" if something wrong could please provide more details.

Lesson02: Eugene.ovdiyuk

---

03-make/make_simplest/Makefile
03-make/soup_task/Makefile
03-make/soup_task/food-market/porridge
03-make/soup_task/food-market/potato
03-make/soup_task/food-market/water
03-make/soup_task/kitchen/table/spoon

Lesson 03 make

---

03-make/make_soup/food-market/carrot.txt
03-make/make_soup/food-market/potato.txt
03-make/make_soup/food-market/salt.txt
03-make/make_soup/food-market/water.txt
03-make/make_soup/makefile

Project with basic soup maker added for review
Signed-off-by: Oleksandr Siruk <alexsirook@gmail.com>

Lesson_03: Add project for making basic soup

---

04-KernelModule/Makefile
04-KernelModule/log.txt
04-KernelModule/simpleModule.c

Homework for lesson 04 added for review. 
Makefile and sourcefile were checked by checkpatch.pl.
note: there was a lot of unexpected spaces and tabs in code example in presentation.
Signed-off-by: Oleksandr Siruk <alexsirook@gmail.com>

Lesson_04: Add simple kernel module sourcefile, makefile and log

---

02-Git/Makefile
02-Git/README.md
02-Git/main.c

Please review and pull if all right.

Lesson2(Git) - Task finished

---

03-bash/task1.sh

Signed-off-by: Oleksandr Siruk <alexsirook@gmail.com>
Script with partial functionality from bash homework added for review.

Lesson_03: Add bash scrit with partial functionality from homework task

---

03-bash/task1.sh
03-bash/task2.sh

03-Bash homework
Could you please take a look at my homework
Signed-off-by: Serega911 <pasechnuy.sergey@gmail.com>

03-Bash homework

---

03-bash/task1.sh
03-bash/task2.sh

I added the entire script at once since the script was created before the task was added to the main branch.
The work in progress.

Lesson 03/bash: Add a script with a basic logic

---

03-bash/task1.sh
04-KernelModule/README.md

Please review and pull if all right.

Lesson 3: Bash, Task1 - Add bash script with partially implemented functionality

---

04-KernelModule/Makefile
04-KernelModule/README.md
04-KernelModule/log.txt
04-KernelModule/mymodule.c

Initial commit. Contains Makefile, source code and
log capture. For build and startup instructions see README.md
Signed-off-by: Serhii Perederii <serhii.perederii@globallogic.com>

04-KernelModule: Add finished homework task

---

04-KernelModule/Makefile
04-KernelModule/module_1.c
04-KernelModule/out.txt

Signed-off-by: Dmitriy Ganshin <d.hanshyn@gmail.com>

Lesson_04: Add simple kernel module, Makefile and out.txt

---

04-KernelModule/simple_kernel_module/Makefile
04-KernelModule/simple_kernel_module/simple_kernel_module.c
04-KernelModule/simple_kernel_module/simple_kernel_module_log_fail
04-KernelModule/simple_kernel_module/simple_kernel_module_log_success

Homework04

---

04-KernelModule/Makefile
04-KernelModule/hello_printk.c
04-KernelModule/log.sh
04-KernelModule/log.txt

log.sh is multi-runner wich automates insmod and rmmod with
differents parametrs.
log.txt is example of work log.sh
In module was used printk(KERN_SOH"%d for showing all
diversity of kernel's output.
Signed-off-by: Illia Iorin <illia.iorin@gloaballogic.com>

lesson04: Implement simple module

---

02-Git/Makefile
02-Git/main.c

This commits was reviewed by you earlier (in PR #59 ).
And spaces instead tabs was used.
But prev. PR (#59 ) was closed after REcreated branch "temp".
I just wanted add last fixed commits (after interactive rebase) in branch "temp" but not in "HEAD:temp" with command: git_push_origin_:temp
and after that branch "temp" was deleted.

Lesson02: Ivan Parfyonov

---

06-TimeManagement/Makefile
06-TimeManagement/time_management.c

Signed-off-by: serega911 <pasechnuy.sergey@gmail.com>

06-Time management: add kernel module with time management
